produtos = {
            "REFRESCO XERETA FRESH PET 6X530ML FRUTAS CITRICAS",
            "REFRESCO XERETA FRESH PET 6X530ML UVA",
            "REFRESCO XERETA FRESH PET 6X1L FRUTAS CITRICAS",
            "REFRESCO XERETA FRESH PET 6X1L UVA",
            "AGUA TONICA VITTAL GOLD PET 6X1L",
            "AGUA TONICA VITTAL PET 6X1L LIMAO",
            "AGUA TONICA VITTAL PET 6X1L ZERO",
}